name: CI-CD Pipeline for ETL App

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main

jobs:
  test-and-validate:
    name: Run Tests and Validations
    runs-on: ubuntu-latest
    # This job runs on pushes to development and PRs to main
    if: github.event_name == 'pull_request' || github.ref == 'refs/heads/development'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Unit and Integration Tests
        run: pytest tests/

      - name: Validate Dockerfile (Build Only)
        # This step only runs for Pull Requests to main, as a final check
        if: github.event_name == 'pull_request'
        run: docker build . --tag temp-image:latest

  build-and-deploy-manifest:
    name: Build Image and Update Config Repo
    runs-on: ubuntu-latest
    needs: test-and-validate
    # This job ONLY runs after a merge/push to the main branch
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      - name: Checkout app-repo code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Azure Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and Push Docker Image
        id: build-and-push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.ACR_LOGIN_SERVER }}/etl-app:${{ github.sha }}

      - name: Checkout config-repo to update manifests
        uses: actions/checkout@v3
        with:
          repository: Burhan523/cloudwave-aks-config
          token: ${{ secrets.CONFIG_REPO_PAT }}
          path: 'config-repo' # Checkout to a specific subdirectory

      - name: Update Kubernetes Manifest with new Image Tag
        run: |
          cd config-repo
          sed -i 's|image:.*|image: ${{ secrets.ACR_LOGIN_SERVER }}/etl-app:${{ github.sha }}|' deployment.yaml
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions-bot@github.com"
          git add deployment.yaml
          git commit -m "Update image to ${{ github.sha }} for etl-app" || echo "No changes to commit"
          git push