name: CI-CD Pipeline for ETL App

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main

jobs:
  test-and-validate:
    name: Run Tests and Validations
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' || github.ref == 'refs/heads/development'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - run: pip install -r requirements.txt
      - run: pytest tests/
      - if: github.event_name == 'pull_request'
        run: docker build . --tag temp-image:latest

  build-and-update-config:
    name: Build Image and Update Config Repo
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          registry: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      - uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.ACR_LOGIN_SERVER }}/etl-app:${{ github.sha }}

      - uses: actions/checkout@v3
        with:
          repository: Burhanuddin-Nahargarwala/cloudwave-aks-config
          token: ${{ secrets.CONFIG_REPO_PAT }}
          path: 'config-repo'

      - name: Update Kubernetes Manifest with new Image Tag
        run: |
          cd config-repo
          
          JOB_FILE=app/cloudwave-etl/dev/job.yaml

          # Update the image tag in the correct file
          sed -i 's|image:.*|image: ${{ secrets.ACR_LOGIN_SERVER }}/etl-app:${{ github.sha }}|' $DEPLOYMENT_FILE
          
          # Commit the specific, changed file
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions-bot@github.com"
          git add $DEPLOYMENT_FILE
          git commit -m "Update image to ${{ github.sha }} for etl-app" || echo "No changes to commit"
          git push